# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genAlConn <- function(aList, cds) {
    .Call(`_redist_genAlConn`, aList, cds)
}

findBoundary <- function(fullList, conList) {
    .Call(`_redist_findBoundary`, fullList, conList)
}

cppGeneratePartitions <- function(adjList, numBlocks, popSizes, numConstraintLow, numConstraintHigh, popConstraintLow, popConstraintHigh) {
    .Call(`_redist_cppGeneratePartitions`, adjList, numBlocks, popSizes, numConstraintLow, numConstraintHigh, popConstraintLow, popConstraintHigh)
}

countpartitions <- function(aList) {
    .Call(`_redist_countpartitions`, aList)
}

calcPWDh <- function(x) {
    .Call(`_redist_calcPWDh`, x)
}

calc_polsbypopper <- function(new_cds, areas_vec, boundarylist_new, borderlength_mat, pop_vec, aList, discrete = FALSE) {
    .Call(`_redist_calc_polsbypopper`, new_cds, areas_vec, boundarylist_new, borderlength_mat, pop_vec, aList, discrete)
}

segregationcalc <- function(distmat, grouppop, fullpop) {
    .Call(`_redist_segregationcalc`, distmat, grouppop, fullpop)
}

rsg <- function(adj_list, population, Ndistrict, target_pop, thresh, maxiter) {
    .Call(`_redist_rsg`, adj_list, population, Ndistrict, target_pop, thresh, maxiter)
}

sample_partition <- function(aList, aMat, num_partitions, num_samples, threads = 1L) {
    .Call(`_redist_sample_partition`, aList, aMat, num_partitions, num_samples, threads)
}

swMH <- function(region, nsims, beta = 0.0, ssd_denom = 1.0, anneal_beta_population = 0L, anneal_beta_compact = 0L, anneal_beta_segregation = 0L, anneal_beta_similar = 0L, exact_mh = 0L, adapt_eprob = 0L, adapt_lambda = 0L, adapt_beta = "none", compactness_measure = "fryer-holden", num_hot_steps = 0L, num_annealing_steps = 0L, num_cold_steps = 0L) {
    .Call(`_redist_swMH`, region, nsims, beta, ssd_denom, anneal_beta_population, anneal_beta_compact, anneal_beta_segregation, anneal_beta_similar, exact_mh, adapt_eprob, adapt_lambda, adapt_beta, compactness_measure, num_hot_steps, num_annealing_steps, num_cold_steps)
}

